namespace VarAstroMasters.Shared.Static;

public static class Keywords
{
    public const string CORS_Policy = "CORS_Policy";
    public const string JWT_Issuer = "Jwt:Issuer";
    public const string JWT_Key = "Jwt:Key";
    public const string JWT_Bearer_Token = "bearerToken";
    public const string DarkMode = "DarkMode";
    public const string AuthType = "jwt";
    public const string Role_User = "User";
    public const string Role_Admin = "Administrator";
    public const string Client_HTTP_Bearer_Header = "bearer";
    public const string LcJdFormatHeliocentric = "heliocentric";
    public const string LcJdFormatGeocentric = "geocentric";
    public const string LcFilterNoFilter = "NoFilter";
    public const string LcFilterU = "U";
    public const string LcPhotometricInstrumental = "instrumental";
    public const string LcPhotometricStandard = "standard";
    public const string DefaultPageTitle = "Var Astro";
    public const string DefaultDateTimeFormat = "dd.MM.yyyy HH:mm";
    public const string AlertSuccess = "success";
    public const string AlertInfo = "info";
    public const string AlertDanger = "danger";
    public const string AcceptedImageFormats = "image/png, image/jpeg, image/gif";
    public const string NotFoundMessage = "Objekt nenájdený.";
    public const string AlreadyExists = "Objekt so zhodným identifikátorom už existuje.";
    public const string NotPublished = "Tento záznam nie je verejný.";
    public const string CurveNotPublished = "Toto pozorovanie nemá zverejnenú krivku.";
    public const string MapNotPublished = "Toto pozorovanie nemá zverejnenú mapu.";
    public const string RegisterFailed = "Registrácia zlyhala.";
    public const string RegisterSucceeded = "Registrácia úspešná.";
    public const string InvalidCredentials = "Nesprávne údaje.";
    public const string InvalidToken = "Vaša požiadavka neobsahuje autentifikačný token. Ste prihlásený?";
    public const string PostSucceeded = "Záznam bol vytvorený.";
    public const string DeleteSucceeded = "Záznam bol odstránený.";
    public const string PutSucceeded = "Záznam bol upravený.";
    public const string PutFailed = "Úprava záznamu bola neúspešná.";
    public const string PostFailed = "Vytvorenie záznamu bolo neúspešné.";
    public const string DeleteFailed = "Odstránenie záznamu bolo neúspešné.";
    public const string CannotDeletePrimaryCat = "Primárny katalóg nie je možné odstrániť.";
    public const string SearchSucceeded = "Pre zadaný výraz bolo nájdených";
    public const string SearchFailed = "Pre zadaný výraz neboli nájdené žiadne výsledky.";
    public const string CannotDeletePrimaryCatalog = "Primárny katalóg nie je možné vymazať.";
    public const int DefaultFilter = 0;
    public const string FormStringLength = "Pole musí obsahovať {2} až {1} znakov.";
    public const string FormValueRange = "Hodnota pola musí byť v rozmedzí {2} až {1}.";
    public const string FormFieldRequired = "Toto pole je povinné.";
    public const string FormInvalidFormat = "Táto hodnota nie je pre toto pole platná.";
    public const string FormPasswordMismatch = "Heslá sa musia zhodovať.";
}